apiVersion: batch/v1
kind: CronJob
metadata:
  name: calendar-sync
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600
      template:
        spec:
          containers:
          - name: calendar-sync
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: CONFIG_PATH
              value: "/data/config.yaml"
            volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /data/config.yaml
              subPath: config.yaml
            - name: google-creds
              mountPath: /data/google_client_secret.json
              subPath: google_client_secret.json
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
          restartPolicy: Never
          volumes:
          - name: config
            secret:
              secretName: {{ .Values.config.configMapName }}
          - name: google-creds
            secret:
              secretName: {{ .Values.secrets.googleCredentialsSecret.name }}
          - name: data
            persistentVolumeClaim:
              claimName: {{ .Values.pvc.name }}
