apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.googleCredentialsSecret.name }}
type: Opaque
data:
  google_client_secret.json: {{ .Values.secrets.googleCredentialsSecret.data.google_client_secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.googleCredentialsSecret2.name }}
type: Opaque
data:
  google_client_secret2.json: {{ .Values.secrets.googleCredentialsSecret2.data.google_client_secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.configMapName }}
type: Opaque
data:
  config.yaml: {{ .Values.config.content }}
