image:
  repository: ghcr.io/dimonb/calendar-sync/calendar-sync
  tag: latest
  pullPolicy: IfNotPresent

schedule: "*/5 * * * *"

uptrace:
  dsn: 

oltpExporterEndpoint: "http://infra-tempo.infra:4317"

deployEnv: "development"
logLevel: "DEBUG"

secrets:
  googleCredentialsSecret: 
    name: calendar-sync-secrets
    data:
      google_client_secret: 
      
  googleCredentialsSecret2:
    name: calendar-sync-secrets2
    data:
      google_client_secret:

  ghcrSecret:
    name: ghcr-secret
    data:
      dockerconfigjson: 

config:
  configMapName: calendar-sync-config
  content:

sync_window_days: 14

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

pvc:
  name: calendar-sync-pvc
  accessMode: ReadWriteOnce
  storageClassName: 
  size: 1Gi
