name: Deploy Calendar Sync Chart to Kubernetes

on:
  push:
    paths:
      - '**'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Log in to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ hashFiles('calendar_sync/**', 'Dockerfile', 'pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/calendar-sync:${{ github.sha }} 
          ghcr.io/${{ github.repository }}/calendar-sync:${{ hashFiles('calendar_sync/**', 'Dockerfile', 'pyproject.toml') }}
          ghcr.io/${{ github.repository }}/calendar-sync:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache